### ISSUE TITLE
Only read `tas` for relevant grid points and times

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#10]
We might be able to speed up `processEnsemble` a lot if we could find a way to have R only read in `tas` for the grid points and times we want.

**Comment by geanders** [comment]
We may be able to do this by setting `colClasses` to NULL for any columns we don't want: http://stackoverflow.com/questions/5788117/only-read-limited-number-of-columns-in-r
We'd need to move the `closest_point` calculation up in `processEnsemble` to do that before `readtas`, then we'd need another argument to `readtas` to specify which columns to read as non-NULL.

**Comment by ColinAE** [comment]
I don't think it can be done. The .csv file format is extremely simple, being delimited by only commas and newline characters. The system cannot tell where on the storage device each individual column begins. This means it must read the entire file whenever fetching any piece of data. The individuals on stackoverflow seem to be using the term "read" in a non-literal way. The system is still literally performing the read operations from the storage device, but is then discarding the data that the user did not want. 

There may be some fancy feature or technique that I am not aware of, however. I will continue looking into it.

**Comment by geanders** [comment]
Makes sense. I might use `system.time()` to compare the time it takes to pull in everything in tas versus just a couple of columns. If this helps at all, there should be a pretty big gain for that comparison.

**Comment by geanders** [comment]
Eh. I compared, and it is a bit faster, but not crazy:

```
example_tas <- "/Users/brookeanderson/Downloads/sample/cmip5/rcp85/bcc1/r1i1p1/tas_NorthAmerica_12mo.csv"
(time_1 <- system.time(read.csv(example_tas, header = FALSE)))
#    user  system elapsed 
#   42.246   1.112  43.439 
(time_2 <- system.time(read.csv(example_tas, header = FALSE,
                      colClasses = c("numeric", rep(NULL, 863)))))
#   user  system elapsed 
#  36.700   0.623  37.341 
```

This is the most extreme case, too-- reading in every column versus just one.

I don't think it's speeding it up enough to make it worth making this issue a high priority. Let's keep the issue open, and we can continue to think about it, but it's not the big gain I was hoping it would be, so let's wait until we fix other things before we re-visit.

**Comment by geanders** [comment]
Based on Dr. Barnes comments, it won't be worthwhile optimizing this. Instead, we'll (someday) want to allow reading in directly from a netCDF file, which would by-pass this issue.
