### ISSUE TITLE
Ensure we're following all suggestions for C++ code in packages

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#13]
Check against suggestions at: http://r-pkgs.had.co.nz/src.html.

**Comment by ColinAE** [comment]
The C++ code is now following most of the suggestions from the link. I had to mess around with some stuff to make it portable, but things are looking good. 

We still need to create an .onLoad function like the link suggests, but I'm not sure where to put it.

**Comment by geanders** [comment]
Okay, I'll check into the `.onLoad` thing. When I try to run now with the new pull from you, I'm getting some errors in `RcppExports.cpp`. Maybe these are things you've resolved since you did that pull request, though? I'll try again once I merge in your next pull.
