### ISSUE TITLE
Closure documentation

### ISSUE THREAD

**Issue by ColinAE** [geanders/futureheatwaves#26]
Dr. Anderson,

How do you think the closure functions should be documented?

**Comment by geanders** [comment]
I think the best strategy would be to document them through the documentation for the function that writes each closure. We can put in the `@return` field that it returns a function that does ..., and then we can add a `@note` entry to more fully describe the closure created.

**Comment by ColinAE** [comment]
I've mostly expanded the documentation on the closures. The @returns now give a short description of the closure that is returned. I have put information about the closure's parameters inside @notes. Is what I've done acceptable?

**Comment by geanders** [comment]
I'll check on your next pull request.

**Comment by geanders** [comment]
I think we're okay on this now.
