### ISSUE TITLE
Default file names for `tasFilenames`, etc

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#29]
Consider giving `coordinateFilenames`, `tasFilenames`, and `timeFilenames` defaults of our file names for `gen_hw_set` to make our runs easier. I don't feel strongly about this, though-- up to you, Colin.

**Comment by ColinAE** [comment]
I took the defaults away since I didn't believe it was likely that other users would have file names corresponding to ours and so it just dirties up the code. To make the runs easier, you can just save a command that calls gen_hw_set with the parameters that you want in a file.

**Comment by geanders** [comment]
That sounds good.
