### ISSUE TITLE
Add another heatwave definition

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#32]
Before we publish, we'll want to show how to pop in a different heatwave definition. This will require creating a function with an alternative heatwave definition and also documenting how to exchange it with the default definition.

**Comment by ColinAE** [comment]
I copied the R heatwave function into another file and altered the default for the "days" parameter from 2 to 1. The file is currently in the R directory of the project. Should it stay here or should it be moved?

**Comment by geanders** [comment]
The R directory is the right place for it.
