### ISSUE TITLE
Bug in C++ id heatwaves function

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#41]
Identifying heatwaves at values below the cutoff threshold.

**Comment by ColinAE** [comment]
The latest pull request may fix this problem. At the very least, the values should be saner now.

**Comment by geanders** [comment]
Just ran it. The values are definitely saner. And it's super fast. I'm running with R right now and I'll compare results.

**Comment by geanders** [comment]
Nope, it's still not giving the same values as the R function that it's supposed to do the same thing as. It's still giving some 1-day heatwaves, too.

**Comment by geanders** [comment]
But, wow, is it faster than the R one!

Try the following to get it to run within the `gen_hw_set` function: 

```
out <- "~/tmp/results"

dataFolder <- system.file("cmip5", package = "futureheatwaves")
citycsv <- system.file("cities.csv", package = "futureheatwaves")

IDheatwavesFunction <- "IDHeatwavesCPPwrapper"
thresholdBoundaries <- c(2061, 2080)
projectionBoundaries <- c(2061, 2080)
referenceBoundaries <- c(2030, 2040)
printWarning <- FALSE
probThreshold <- 0.98

coordinateFilenames <- "latitude_longitude_NorthAmerica_12mo.csv" 
tasFilenames <- "tas_NorthAmerica_12mo.csv"
timeFilenames <- "time_NorthAmerica_12mo.csv"

ex <- gen_hw_set(out = out,
                 dataFolder = dataFolder,
                 citycsv = citycsv,
                 coordinateFilenames = coordinateFilenames,
                 tasFilenames = tasFilenames,
                 timeFilenames = timeFilenames,
                 IDheatwavesFunction = IDheatwavesFunction,
                 probThreshold = 0.98,
                 thresholdBoundaries = thresholdBoundaries,
                 projectionBoundaries = projectionBoundaries,
                 referenceBoundaries = referenceBoundaries
                 )
```

(You can change `out` if you want-- I'm just having it go to a `results` directory in my `tmp` directory. Keep the file paths the same for the ones with `system.file` once you load `futureheatwaves` as a package, though-- this will find the example datasets in the package for you.)

**Comment by geanders** [comment]
Also, re-sync your version with the master-- I found a bug in the R wrapper for the C++ function that you'll need to have the good version of to get this going.

**Comment by ColinAE** [comment]
I see the change you have made. Don't we want the user to be able to customize the number of days of the heatwave definition?

**Comment by geanders** [comment]
Right now, I'd rather that we keep the required format for the heatwave definition simple (i.e., only required arguments are the dataframe and threshold). Now that we're hoping that others will use this, some will likely be writing their own definitions that don't require (or have a fixed value for) days. So, yes, let's put the number of days required as a fixed value rather than an argument in all of our IDheatwave functions for now. 

Otherwise, we'd need to pass `days` all the way through from `gen_hw_set` in something like `global`. That might be worth adding later, but let's keep it simpler now. Define the fixed `days` as a variable, though, at the very start of the id function (see the code for `IDHeatwavesR`), and then use `days` throughout the rest of the code, and it will be easy to expand later to allow that as a customizable choice.

**Comment by ColinAE** [comment]
Try it with this next pull request. If this doesn't work, it might be a deeper problem than my just my logic. I'm going to bed soon, but I will try to run everything tomorrow.

**Comment by geanders** [comment]
No, it's still giving single-day heatwaves (although, I think, different ones than before).

**Comment by ColinAE** [comment]
You're going to have to show me how this new version is executed. Now I'm getting an "unused arguments" error.

**Comment by geanders** [comment]
No problem, I can show you today.

**Comment by geanders** [comment]
I checked through the R wrapper function for this, and that's not the problem. The R code before the C++ function is working as expected, and the C++ function is still picking out single-day heatwaves.

**Comment by ColinAE** [comment]
Alright, I'll have to run through it again. Can you send me your results from both functions just so I have something to compare against when I do my own runs?

**Comment by geanders** [comment]
Yes. Also, for debugging, I found it useful to put in `browser()` right at the start of the C++ wrapper ID heatwaves function, then the function run stops when it gets to that part of the function and lets you walk through line by line and see what everything looks like.
