### ISSUE TITLE
Check: would the citycsv work okay if the user put the columns in a different order?

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#61]

**Comment by ColinAE** [comment]
Not with the current implementation, but that could be changed. If we are reading in the header, then we could access the columns with the '$' notation instead of indexing into both the rows and columns.

**Comment by geanders** [comment]
We'll want to base this on column name and also, especially moving to netCDF, allow the user to specify what those column names are (some people would have "lon" and "lat", some would have "longitude" and "latitude").
