### ISSUE TITLE
Don't write out minimums

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#63]
This was for bug checking. We don't need it anymore.

**Comment by ColinAE** [comment]
Shall I remove it completely or just deactivate the block?

**Comment by geanders** [comment]
I can take it all the way out. I'm getting ready to work through some of the code on closures, and I think I'm going to take out the writing thresholds stuff completely. The heatwave data frames include the threshold values for each community for each ensemble member already, and know that I've written the `apply_all_models` function, it will be easy to pull that out from there. That will simplify the output directory a bit. If you could work on the C++ code, that would be awesome-- I don't really know how to de-bug that. (Also, as a note, I've converted the code so that now the code expects the latitude and longitudes for the `citycsv` file to use the same way of expressing latitude and longitude as the `coordinate` file for the projections. That means that the code might not work right if you're using an old file for `citycsv`-- use the one I've got in `inst` now and you'll be fine.)

**Comment by ColinAE** [comment]
I just sent you an email about that. The C++ problem should be an easy fix, but I can't test it. I just issued a pull request with the possible solution.
