### ISSUE TITLE
For C++ function to ID heatwaves, take out `first.hw.day`

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#67]
We don't need this anymore. I'm working on taking it out of the R functions, but we can take it out from the C++ function, too. This column was a relic from using this id function for some epidemiology studies. This means that the dataframe returned from the ID heatwaves functions should only have two new columns: `hw` and `hw.number` (these are in addition to the `date` and `tmpd` columns it came in with).

**Comment by ColinAE** [comment]
I have taken out all logic involved with first.hw.day.

**Comment by ColinAE** [comment]
Although, it should be noted that I do not know what effect this will have far beyond the heatwave identification part.

**Comment by geanders** [comment]
I checked with the R ID heatwaves functions and we're fine. We weren't ever using that column again.
