### ISSUE TITLE
Keep the R / C++ option?

### ISSUE THREAD

**Issue by geanders** [geanders/futureheatwaves#8]
We'll need to decide if we want to keep the C++ option. Are you using it now, or did you not get around to integrating it with the main functions? I think, especially if we want to put this on CRAN, we'd need to do some special things if we're including C++ code (not a huge problem, just something to think about).

**Comment by ColinAE** [comment]
I have always been using C++ whenever I run the code. It works perfectly as far as I can tell. I'm not sure what you mean when you mention it being integrated with the main functions.

**Comment by geanders** [comment]
Yep, I figured that out as I worked through some of the code. Sorry, this was just something I was confused about the first pass through putting the code in the package.
